remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

title: "PortSwigger Web Security Academy â€“ Full Lab Writeups"
description: "Complete categorized writeups for all PortSwigger labs"
